spring.application.name=demo-kafka-skill

# Kafka topic
kafka.topic.posts=posts-topic

# Kafka common (SSL on port 9093)
kafka.arch.common.bootstrap-servers=localhost:9093
kafka.arch.common.schema-registry=http://localhost:8081
kafka.arch.common.enable-connection-ssl-protocol-mode=true
kafka.arch.common.ssl-trust-store-location=classpath:ssl/kafka.truststore.p12
kafka.arch.common.ssl-trust-store-password=changeit
kafka.arch.common.ssl-key-store-location=classpath:ssl/kafka.client-keystore.p12
kafka.arch.common.ssl-key-store-password=changeit

# Kafka producer
kafka.arch.producer.ack-producer-config=all
kafka.arch.producer.compress-type=snappy
kafka.arch.producer.type-partitioner=UniformStickyPartitioner

# Kafka consumer
kafka.arch.consumer.consumer-group-id=demo-kafka-skill-group
kafka.arch.consumer.ack-consumer-config=manual
kafka.arch.consumer.event-auto-offset-reset-config=latest
kafka.arch.consumer.enable-avro-reader-config=false
